Repository WE-ARE-RACCOONS/postgraduate-front, pull requests merged in 2024-07, with the labels that each got.

#276 RAC-395 feat: 대학원생 상세프로필 인증마크 유무
  src/app/senior/info/[seniorId]/page.tsx
  src/components/Card/ProfileCard/ProfileCard.tsx
  src/components/Text/AuthLabeledText/AuthLabeledText.tsx
  src/types/card/profileCard.ts
  src/types/profile/seniorProfile.ts
Labels: ✨ Feature, 💅 style

#278 RAC-407 fix: 홈 화면 탭 디자인 수정 및 00대학교 타입 수정
  src/components/Bar/UnivTapBar/UnivTapBar.tsx
  src/constants/tab/ctap.ts
  src/types/tap/tap.tsx
Labels: 💅 style

#280 RAC-408 fix: 멘토링 진행X 후배 내멘토링 페이지 UI 수정
  src/components/Bar/TapBar/JuniorTab/JTabBar.styled.ts
  src/components/Bar/TapBar/JuniorTab/JTabBar.tsx
  src/components/Bar/TapBar/SeniorTab/STabBrar.styled.ts
  src/components/Card/IntroCard/IntroCard.styled.ts
  src/components/MentoringNotYet/MentoringNotYet.styled.ts
  src/components/MentoringNotYet/MentoringNotYet.tsx
  src/components/MentoringNotYet/index.tsx
  src/constants/mentoring/my.ts
Labels: ✨ Feature, 💅 style

#281 RAC-408 feat: 내멘토링 페이지 버튼 클릭 이벤트 추가
  src/components/MentoringNotYet/MentoringNotYet.tsx
Labels: ✨ Feature

#284 RAC-413 fix: 교수님 필드 수정 및 회원가입 상수화
  src/app/page.tsx
  src/app/search-results/page.tsx
  src/app/signup/select/common-info/matching-info/page.tsx
  src/app/signup/select/common-info/senior-info/field/page.tsx
  src/app/signup/select/common-info/senior-info/lab/page.tsx
  src/app/signup/select/common-info/senior-info/major/page.tsx
  src/app/signup/select/page.tsx
  src/components/Button/SignUpBtn/SignUpBtn.tsx
  src/constants/signup/common.ts
  src/constants/signup/junior.ts
  src/constants/signup/senior.ts
Labels: 🐞 BugFix, 🛠️ Refactor
